Models/Kullanici.cs
using System;
using System.Collections.Generic;
using System.Security.Claims;

namespace HospitalAppointmentSystem.Models
{
    public partial class Kullanici
    {
        public Kullanici()
        {
            Randevus = new HashSet<Randevu>();
        }

        public int KullaniciId { get; set; }
        public string Email { get; set; } = null!;
        public string Sifre { get; set; } = null!;
        public string Adi { get; set; } = null!;
        public string Soyadi { get; set; } = null!;
        public string Cinsiyet { get; set; } = null!;
        public DateTime? DogumTarihi { get; set; }
        public string? TelefonNumarasi { get; set; }
        public string KullaniciRole { get; set; } = null!;

        public virtual ICollection<Randevu> Randevus { get; set; }
    }
}

Controllers/DoktorsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using HospitalAppointmentSystem.Models;
using Microsoft.AspNetCore.Authorization;

namespace HospitalAppointmentSystem.Controllers
{
    public class DoktorsController : Controller
    {
        private readonly hospitalContext _context;

        public DoktorsController(hospitalContext context)
        {
            _context = context;
        }

        // GET: Doktors
        [Authorize(Roles = "A, U")]
        public async Task<IActionResult> Index()
        {
            var hospitalContext = _context.Doktors.Include(d => d.Poliklinik);
            return View(await hospitalContext.ToListAsync());
        }
        [Authorize(Roles = "A, U")]
        // GET: Doktors/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Doktors == null)
            {
                return NotFound();
            }

            var doktor = await _context.Doktors
                .Include(d => d.Poliklinik)
                .FirstOrDefaultAsync(m => m.DoktorId == id);
            if (doktor == null)
            {
                return NotFound();
            }

            return View(doktor);
        }

        // GET: Doktors/Create
        [Authorize(Roles ="A")]
        public IActionResult Create()
        {
            ViewData["PoliklinikId"] = new SelectList(_context.Polikliniks, "PoliklinikId", "PoliklinikId");
            return View();
        }

        // POST: Doktors/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [Authorize(Roles = "A")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("DoktorId,Adi,Soyadi,Brans,PoliklinikId,Telefon,Mail,Adres,Maas,Cinsiyet")] Doktor doktor)
        {
            if (ModelState.IsValid)
            {
                _context.Add(doktor);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["PoliklinikId"] = new SelectList(_context.Polikliniks, "PoliklinikId", "PoliklinikId", doktor.PoliklinikId);
            return View(doktor);
        }

        // GET: Doktors/Edit/5
        [Authorize(Roles = "A")]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Doktors == null)
            {
                return NotFound();
            }

            var doktor = await _context.Doktors.FindAsync(id);
            if (doktor == null)
            {
                return NotFound();
            }
            ViewData["PoliklinikId"] = new SelectList(_context.Polikliniks, "PoliklinikId", "PoliklinikId", doktor.PoliklinikId);
            return View(doktor);
        }

        // POST: Doktors/Edit/5
        [Authorize(Roles = "A")]
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("DoktorId,Adi,Soyadi,Brans,PoliklinikId,Telefon,Mail,Adres,Maas,Cinsiyet")] Doktor doktor)
        {
            if (id != doktor.DoktorId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(doktor);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!DoktorExists(doktor.DoktorId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["PoliklinikId"] = new SelectList(_context.Polikliniks, "PoliklinikId", "PoliklinikId", doktor.PoliklinikId);
            return View(doktor);
        }

        // GET: Doktors/Delete/5
        [Authorize(Roles = "A")]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Doktors == null)
            {
                return NotFound();
            }

            var doktor = await _context.Doktors
                .Include(d => d.Poliklinik)
                .FirstOrDefaultAsync(m => m.DoktorId == id);
            if (doktor == null)
            {
                return NotFound();
            }

            return View(doktor);
        }

        // POST: Doktors/Delete/5
        [Authorize(Roles = "A")]
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Doktors == null)
            {
                return Problem("Entity set 'hospitalContext.Doktors'  is null.");
            }
            var doktor = await _context.Doktors.FindAsync(id);
            if (doktor != null)
            {
                _context.Doktors.Remove(doktor);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool DoktorExists(int id)
        {
          return (_context.Doktors?.Any(e => e.DoktorId == id)).GetValueOrDefault();
        }
    }
}

Controllers/RandevusController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using HospitalAppointmentSystem.Models;
using Microsoft.AspNetCore.Authorization;

namespace HospitalAppointmentSystem.Controllers
{
    public class RandevusController : Controller
    {
        private readonly hospitalContext _context;

        public RandevusController(hospitalContext context)
        {
            _context = context;
        }

        // GET: Randevus
        [Authorize(Roles = "A")]
        public async Task<IActionResult> Index()
        {
            var hospitalContext = _context.Randevus.Include(r => r.CalismaGun).Include(r => r.Doktor).Include(r => r.Kullanici).Include(r => r.Poliklinik).Include(r => r.Saat);
            return View(await hospitalContext.ToListAsync());
        }

        // GET: Randevus/Details/5
        [Authorize(Roles = "A")]
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Randevus == null)
            {
                return NotFound();
            }

            var randevu = await _context.Randevus
                .Include(r => r.CalismaGun)
                .Include(r => r.Doktor)
                .Include(r => r.Kullanici)
                .Include(r => r.Poliklinik)
                .Include(r => r.Saat)
                .FirstOrDefaultAsync(m => m.RandevuId == id);
            if (randevu == null)
            {
                return NotFound();
            }

            return View(randevu);
        }
        [Authorize(Roles = "A")]
        // GET: Randevus/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Randevus == null)
            {
                return NotFound();
            }

            var randevu = await _context.Randevus.FindAsync(id);
            if (randevu == null)
            {
                return NotFound();
            }
            ViewData["CalismaGunId"] = new SelectList(_context.CalismaGuns, "CalismaGunId", "CalismaGunId", randevu.CalismaGunId);
            ViewData["DoktorId"] = new SelectList(_context.Doktors, "DoktorId", "DoktorId", randevu.DoktorId);
            ViewData["KullaniciId"] = new SelectList(_context.Kullanicis, "KullaniciId", "KullaniciId", randevu.KullaniciId);
            ViewData["PoliklinikId"] = new SelectList(_context.Polikliniks, "PoliklinikId", "PoliklinikId", randevu.PoliklinikId);
            ViewData["SaatId"] = new SelectList(_context.Saatlers, "SaatId", "SaatId", randevu.SaatId);
            return View(randevu);
        }

        // POST: Randevus/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [Authorize(Roles = "A")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("RandevuId,PoliklinikId,DoktorId,KullaniciId,CalismaGunId,SaatId,Aciklama")] Randevu randevu)
        {
            if (id != randevu.RandevuId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(randevu);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!RandevuExists(randevu.RandevuId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["CalismaGunId"] = new SelectList(_context.CalismaGuns, "CalismaGunId", "CalismaGunId", randevu.CalismaGunId);
            ViewData["DoktorId"] = new SelectList(_context.Doktors, "DoktorId", "DoktorId", randevu.DoktorId);
            ViewData["KullaniciId"] = new SelectList(_context.Kullanicis, "KullaniciId", "KullaniciId", randevu.KullaniciId);
            ViewData["PoliklinikId"] = new SelectList(_context.Polikliniks, "PoliklinikId", "PoliklinikId", randevu.PoliklinikId);
            ViewData["SaatId"] = new SelectList(_context.Saatlers, "SaatId", "SaatId", randevu.SaatId);
            return View(randevu);
        }

        // GET: Randevus/Delete/5
        [Authorize(Roles = "A")]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Randevus == null)
            {
                return NotFound();
            }

            var randevu = await _context.Randevus
                .Include(r => r.CalismaGun)
                .Include(r => r.Doktor)
                .Include(r => r.Kullanici)
                .Include(r => r.Poliklinik)
                .Include(r => r.Saat)
                .FirstOrDefaultAsync(m => m.RandevuId == id);
            if (randevu == null)
            {
                return NotFound();
            }

            return View(randevu);
        }

        // POST: Randevus/Delete/5
        [Authorize(Roles = "A")]
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Randevus == null)
            {
                return Problem("Entity set 'hospitalContext.Randevus' is null.");
            }

            var randevu = await _context.Randevus.FindAsync(id);
            if (randevu != null)
            {
                // SaatID'yi al
                // SaatID'yi al
                int? saatIdNullable = randevu.SaatId;

                // Eğer saatIdNullable null değilse, intValue değişkenine atama yap
                int intValue = saatIdNullable ?? 0;


                _context.Randevus.Remove(randevu);

                // İlgili saat dilimini tekrar "secilebilir" yap
                var saat = await _context.Saatlers.FindAsync(saatIdNullable);
                if (saat != null)
                {
                    saat.Secilebilir = true;
                }
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool RandevuExists(int id)
        {
          return (_context.Randevus?.Any(e => e.RandevuId == id)).GetValueOrDefault();
        }
    }
}

Controllers/UyeController.cs
using HospitalAppointmentSystem.Models;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using System.Security.Claims;
using System.Threading.Tasks;

namespace HospitalAppointmentSystem.Controllers
{
    public class UyeController : Controller
    {
        private readonly hospitalContext db;

        public UyeController(hospitalContext context)
        {
            db = context;
        }

        public IActionResult SifreDegistir()
        {
            return View();
        }

       [HttpPost]
public IActionResult SifreDegistir(SifreDegistirViewModel model)
{
    if (ModelState.IsValid)
    {
                var userEmail = HttpContext.User.FindFirstValue(ClaimTypes.Email);
                var kullanici = db.Kullanicis.FirstOrDefault(x => x.Email == userEmail);


                if (kullanici != null && kullanici.Sifre == model.EskiSifre)
        {
            // Eski şifre doğrulandı, yeni şifreyi kaydet
            kullanici.Sifre = model.YeniSifre;
            db.SaveChanges();

            return RedirectToAction("Index", "Home");
        }
        else
        {
            ModelState.AddModelError(string.Empty, "Eski şifreniz yanlış.");
        }
    }

    return View(model);
}



        public IActionResult GirisYap()
        {
            ClaimsPrincipal claimUser = HttpContext.User;

            if (claimUser.Identity.IsAuthenticated)
                return RedirectToAction("Index", "Home");

            return View();
        }

        [HttpPost]
        public async Task<IActionResult> GirisYap(Kullanici k, string ReturnUrl)
        {
            var kullanici = db.Kullanicis.FirstOrDefault(x => x.Email == k.Email && x.Sifre == k.Sifre);

            if (kullanici != null)
            {
                var claims = new List<Claim>
        {
           new Claim(ClaimTypes.NameIdentifier, kullanici.KullaniciId.ToString()), // Include user ID in claims
            new Claim(ClaimTypes.Email, k.Email),
            new Claim(ClaimTypes.Role, kullanici.KullaniciRole),
        };

                ClaimsIdentity identity = new ClaimsIdentity(claims, CookieAuthenticationDefaults.AuthenticationScheme);
                ClaimsPrincipal principal = new ClaimsPrincipal(identity);

                await HttpContext.SignInAsync(principal);

                if (!string.IsNullOrEmpty(ReturnUrl))
                {
                    return Redirect(ReturnUrl);
                }
                else
                {
                    return RedirectToAction("Index", "Home");
                }
            }

            return View();
        }


        public async Task<IActionResult> CikisYap()
        {
            await HttpContext.SignOutAsync(CookieAuthenticationDefaults.AuthenticationScheme);
            return RedirectToAction("Index", "Home");
        }
    }
}

Views/Shared/GirisLayout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - HospitalAppointmentSystem</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/HospitalAppointmentSystem.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">HospitalAppointmentSystem</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Randevu" asp-action="Index">Randevu Al</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Uye" asp-action="GirisYap">Giris Yap</a>
                        </li>
                       
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
       
       
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - HospitalAppointmentSystem</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/HospitalAppointmentSystem.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">HospitalAppointmentSystem</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Polikliniks" asp-action="Index">Polikilinikler</a>
                        </li>
                      
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Doktors" asp-action="Index">Doktorlar</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="CalismaGuns" asp-action="Index">Calisma Gunleri</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Saatlers" asp-action="Index">Saatler</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Randevus" asp-action="Index">Randevular</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Uye" asp-action="GirisYap">Giris Yap</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Uye" asp-action="CikisYap">Cikis Yap</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - HospitalAppointmentSystem - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Views/Shared/admin.cshtml
@using System.Security.Claims
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - HospitalAppointmentSystem</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/HospitalAppointmentSystem.styles.css" asp-append-version="true" />

    <!-- Eklediğimiz CSS kodu başlangıcı -->
    <style>
        #sidebar {
            transition: margin-left 0.5s;
            margin-top: 20px; /* Üst boşluğu ayarlayın */
            background-color: #343a40; /* Sidebar arka plan rengi */
            color: #fff; /* Sidebar metin rengi */
        }

            #sidebar a {
                padding: 16px;
                text-decoration: none;
                font-size: 18px;
                color: #fff;
                display: block;
                transition: background-color 0.3s;
                border-bottom: 1px solid #4CAF50; /* Linkler arasına çizgi ekleyin */
            }

                #sidebar a:hover {
                    background-color: #4CAF50; /* Link üzerine gelindiğinde renk değiştirin */
                }

            #sidebar .nav-item {
                margin-bottom: 5px;
            }

            #sidebar .nav-link {
                transition: padding-left 0.3s;
                color: #fff; /* Dropdown yazı rengi */
            }

                #sidebar .nav-link:hover {
                    padding-left: 20px;
                }

            /* Logo stili */
            #sidebar .navbar-brand {
                padding: 16px;
                font-size: 24px;
                color: #8cff66;
                display: block;
            }

            /* Dropdown menü için stil */
            #sidebar .dropdown-item {
                color: #000; /* Dropdown içindeki yazı rengi */
            }

                #sidebar .dropdown-item:hover {
                    background-color: #8cff66; /* Dropdown üzerine gelindiğinde renk değiştirin */
                }

            /* Kullanıcının e-mail yazan yeri için stil */
            #sidebar #navbarDropdown {
                color: #000; /* E-mail yazan yerin rengi */
            }
    </style>

</head>
<body>
    <div class="container-fluid">
        <div class="row">
            <!-- Sidebar -->
            <nav id="sidebar" class="col-md-3 col-lg-2 d-md-block bg-light sidebar">
                <div class="position-sticky">
                    <ul class="nav flex-column">
                        <li class="nav-item">
                            <span class="navbar-brand">ADMIN SAYFASI</span>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Polikliniks" asp-action="Index">Polikilinikler</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Doktors" asp-action="Index">Doktorlar</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="CalismaGuns" asp-action="Index">Calisma Gunleri</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Randevus" asp-action="Index">Randevular</a>
                        </li>
                      
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Uye" asp-action="CikisYap">Cikis Yap</a>
                        </li>
                    </ul>

                    <ul class="nav flex-column mt-3">
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                @(User.Identity.IsAuthenticated ? User.FindFirst(ClaimTypes.Email)?.Value : "")
                            </a>
                            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <a class="dropdown-item" asp-controller="Profile" asp-action="Index">Profilim</a>
                                <a class="dropdown-item" asp-controller="Uye" asp-action="SifreDegistir">Sifre Degistir</a>
                                <div class="dropdown-divider"></div>
                                <a class="dropdown-item" asp-controller="Uye" asp-action="CikisYap">Cikis yap</a>
                            </div>
                        </li>
                    </ul>
                </div>
            </nav>

            <!-- Content -->
            <main class="col-md-9 ms-sm-auto col-lg-10 px-md-4 mt-4">
                @RenderBody()
            </main>
        </div>
    </div>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Views/Shared/kullanici.cshtml
@using System.Security.Claims
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - HospitalAppointmentSystem</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/HospitalAppointmentSystem.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">HospitalAppointmentSystem</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Polikliniks" asp-action="Index">Polikilinikler</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Doktors" asp-action="Index">Doktorlar</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Randevu" asp-action="Index">Randevu Al</a>
                        </li>
                     
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Uye" asp-action="CikisYap">Cikis Yap</a>
                        </li>
                     
                    </ul>

                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            @(User.Identity.IsAuthenticated ? User.FindFirst(ClaimTypes.Email)?.Value : "")
                        </a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <a class="dropdown-item" asp-controller="Profile" asp-action="Index">Profilim</a>
                            <a class="dropdown-item" asp-controller="Uye" asp-action="SifreDegistir">Sifre Degistir</a>
                            <div class="dropdown-divider"></div>
                            <a class="dropdown-item" asp-controller="Uye" asp-action="CikisYap">Cikis yap</a>
                        </div>
                    </li>


                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>